---
- name: Install nginx
  become: yes
  package:
    name: nginx
    state: installed

- name: http firewall
  become: yes
  firewalld:
    service: http
    zone: public
    permanent: yes
    state: enabled
    immediate: yes

- name: https firewall
  become: yes
  firewalld:
    service: https
    zone: public
    permanent: yes
    state: enabled
    immediate: yes

- name: ssh firewall
  become: yes
  firewalld:
    service: ssh
    zone: public
    permanent: yes
    state: enabled
    immediate: yes

- name: copy nginx file
  become: yes
  template:
    src: nginx_conf.j2
    dest: /etc/nginx/nginx.conf
    owner: nginx
    group: nginx

- name: Reload nginx
  become: yes
  service:
    name: nginx
    state: reloaded
    enabled: yes  
  