---
- hosts: todoapp
  tasks:
    - name: Install nginx
      become: yes
      package:
        name: nginx
        state: installed
    - name: Install mongodb
      become: yes
      package:
        name: mongodb-server
        state: installed
    - name: Install NodeJS
      become: yes
      package:
        name: nodejs
        state: installed
    - name: Install Git
      become: yes
      package:
        name: git
        state: installed
    - name: copy nginx file
      become: yes
      copy:
        src: ../files/nginx.conf
        dest: /etc/nginx/nginx.conf
        owner: nginx
        group: nginx
    - name: Start Nginx
      become: yes
      service:
        name: nginx
        state: reloaded
        enabled: yes
    - name: start mongodb
      become: yes
      service:
        name: mongod
        enabled: yes
        state: started
    - name: Create todoapp user
      become: yes
      user:
        name: "todo-app"
        password: "P@ssw0rd"
    - name: Disable SELinux
      become: yes
      selinux:
        state: disabled
    - name: Clone Todoapp
      become: yes
      git:
        repo: "https://github.com/timoguic/ACIT4640-todo-app.git"
        dest: "/home/todo-app/app"
    - name: firewall https
      become: yes
      firewalld:
        service: https
        zone: public
        permanent: yes
        state: enabled
        immediate: yes
    - name: firewall ssh
      become: yes
      firewalld:
        service: ssh
        zone: public
        permanent: yes
        state: enabled
        immediate: yes
    - name: firewall http
      become: yes
      firewalld:
        service: http
        zone: public
        permanent: yes
        state: enabled
        immediate: yes
    - name: npm install
      become: yes
      npm:
        path: "/home/todo-app/app"
    - name: permissions
      become: yes
      file:
        path: "/home/todo-app"
        state: directory
        recurse: yes
        mode: '0755'
        owner: "todo-app"
        group: "todo-app"
    - name: copy todoapp.service
      become: yes
      copy:
        src: ../files/todoapp.service
        dest: /lib/systemd/system/todoapp.service
    - name: database file copied
      become: yes
      copy:
        src: ../files/database.js
        dest: "/home/todo-app/app/config/database.js"
    - name: daemons reload
      become: yes
      systemd:
        daemon_reload: yes
    - name: start todoapp
      become: yes
      service:
        name: todoapp
        enabled: yes
        state: started